### ISSUE TITLE
M1 칩 맥에서 clovasee 임포트 에러

### ISSUE THREAD

**Issue by whogodemo** [naver/clova-face-kit#4]
안녕하세요. 배포된 링크에는 m1 칩 맥을 위한 릴리즈 파일이 없어서요. 그래서 인텔 칩 맥을 위한 릴리즈 파일을 다운로드 했는데, 에러가 뜨네요.. 제 os는 arm64인데, 다운받은 릴리즈파일은 x86_64라서 에러가 뜨는것 같아요.
에러메세지는 다음과 같습니다.

from clovasee_ import *  # pylint: disable=import-error
ImportError: dlopen(/Users/jerry/afoter-ai-api/venv/lib/python3.8/site-packages/clovasee_.cpython-38-darwin.so, 0x0002): Library not loaded: /usr/local/opt/llvm/lib/libomp.dylib
  Referenced from: /Users/jerry/afoter-ai-api/venv/lib/python3.8/site-packages/clovasee_.cpython-38-darwin.so
  Reason: tried: '/usr/local/opt/llvm/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)

혹시 M1 칩 맥에서 clovasee를 임포트할 수 있는 방법이 있을까요?

**Comment by junhee-yoo** [comment]
안녕하세요. :)

clovasee에 관심을 가져주셔서 감사합니다. 🙇 

첨부해주신 log의 내용으로 보아 현재 시스템에 `libomp`가 설치되어 있지 않은 것 같습니다.
XCode의 기본 clang 및 clang++은 openmp 기능을 지원하지 않는 것으로 알고 있어 [`brew`](https://formulae.brew.sh/formula/libomp)를 이용해 따로 설치하셔야 하며, 해당 lib을 찾을 수 있도록 LD_LIBRARY_PATH 등을 설정하셔야 합니다.
그러나, 위 방식으로 libomp 설치하신 후에는 아마 지원하지 않는 platform이라는 메세지가 출력될겁니다. 😢 

clovasee의 release 당시 M1 기기가 많이 보급되어있지 않았어서 M1용으로 build한 산출물이 없습니다.
현재 M1용 python macos 산출물에 대해 내부검토 중에 있으며, 진행되는 대로 말씀드리겠습니다.

감사합니다. 😃

**Comment by junhee-yoo** [comment]
안녕하세요. :)

답변에 오랜시간이 걸려 죄송합니다.
안타깝게도 팀 내부에서 많은 논의를 한 결과, python m1 processor를 당장은 지원하지 않는 방향으로 결론을 내었습니다. 🙇‍♂️

원하시는 결과를 드리지 못해 다시 한번 죄송합니다. 🙇‍♂️
