### ISSUE TITLE
Android Emulator(WebCam) faces return null

### ISSUE THREAD

**Issue by Sungsoooo** [naver/clova-face-kit#5]
현재 안드로이드 에뮬레이터를 통해 테스트를 진행하고 있는데

bottom sheet에서 Performance,  Native Total, Detector 외에는 아무것도 변하지 않고 있어
render 함수에서 result.face.faces.size 를 로그 찍어봤는데 0으로 출력되고 있습니다.

혹시 webcam을 사용하는 에뮬레이터에서는 분석이 불가능한가요?

**Comment by junhee-yoo** [comment]
안녕하세요. :)

Webcam으로 들어오는 영상이더라도 Face 정보가 잡혀야 맞을 것 같은데요.
혹 camera의 출력을 그대로 넘기신게 아닌가 추측이 됩니다.

https://github.com/naver/clova-face-kit/blob/9d28cf49b5d9dc0713686f37b796577b31e1d3b0/examples/android/app/src/main/java/ai/clova/see/example/CameraFragment.kt#L392

이 부분을 참고하여 설정 및 instance 생성 부분을 한번 확인해 보시겠어요?

**Comment by Sungsoooo** [comment]
> 
말씀해주신 부분 옵션 설정 값입니다.

`val faceOptions = ai.clova.see.face.OptionsBuilder()
                            .setBoundingBoxThreshold(0.9f)
                            .setInformationToObtain(ai.clova.see.face.Options.FEATURES or
                                    ai.clova.see.face.Options.EULER_ANGLES or
                                    ai.clova.see.face.Options.SPOOFS or
                                    ai.clova.see.face.Options.BOUNDING_BOXES or
                                    ai.clova.see.face.Options.CONTOURS)
                            .setResizeThreshold(320)
                            .setMinimumBoundingBoxSize(0.1f)
                            .build()
                        Pair(
                            ClovaSeeRunResult(
                                clovaSee.run(bitmap, faceOptions),
                                ai.clova.see.body.Result(Segment(0)),
                                ai.clova.see.ocr.Result(Document())
                            ),

                            clovaSee.getMeasureResult()
                        )`

sample app 클론 후 실행 할 때도 역시 아무것도 분석이 되지 않고 있습니다.

![Uploading 스크린샷 2022-11-04 오후 5.39.42.png…]()

**Comment by Sungsoooo** [comment]
> 안녕하세요. :)
> 
> Webcam으로 들어오는 영상이더라도 Face 정보가 잡혀야 맞을 것 같은데요. 혹 camera의 출력을 그대로 넘기신게 아닌가 추측이 됩니다.
> 
> https://github.com/naver/clova-face-kit/blob/9d28cf49b5d9dc0713686f37b796577b31e1d3b0/examples/android/app/src/main/java/ai/clova/see/example/CameraFragment.kt#L392
> 
> 이 부분을 참고하여 설정 및 instance 생성 부분을 한번 확인해 보시겠어요?

android sample code clone후 실행 했는데도 같은 현상 발생하며 아래 에러 로그가 발생하는데 저 로그가 분석이 안되는 원인일까요?
W/libc: Access denied finding property "ro.hardware.chipname"
W/ncnn: syscall error -1

**Comment by junhee-yoo** [comment]
안녕하세요. 응답이 늦어 죄송합니다.

확인한 결과 해당 이슈는 Android emulator와 Android 실 기기가 카메라로부터 입력으로 가져오는 image buffer의 format이 서로 상이하여 발생하는 것이었습니다. 올려주신 스크린 샷이 원인을 찾는 실마리가 되었습니다. 감사합니다. 🙇

자세한 내용은 후술하고 @Sungsoooo 님께 제안드리는 해결방안은 [yuv420ToNV21 함수](https://github.com/naver/clova-face-kit/blob/9d28cf49b5d9dc0713686f37b796577b31e1d3b0/examples/android/app/src/main/java/ai/clova/see/example/ImageProcessor.java#L78)에 emulator의 image format에 맞춰 변환하는 내용을 추가하는 것입니다.

```java
    private static byte[] yuv420ToNV21(Image image) {
        ByteBuffer yBuffer = image.getPlanes()[0].getBuffer();
        ByteBuffer uBuffer = image.getPlanes()[1].getBuffer();
        ByteBuffer vBuffer = image.getPlanes()[2].getBuffer();

        final int ySize = yBuffer.remaining();
        final int vuSize = (image.getPlanes()[2].getPixelStride() == 1 ? uBuffer.remaining() + vBuffer.remaining() : vBuffer.remaining() + 1);
        byte[] nv21 = new byte[ySize + vuSize];

        yBuffer.get(nv21, 0, ySize);
        for (int i = ySize; i < nv21.length; i += 2) {
            nv21[i] = vBuffer.get();
            nv21[i + 1] = uBuffer.get();
        }

        return nv21;
    }
```


# 자세한 설명

https://github.com/naver/clova-face-kit/blob/9d28cf49b5d9dc0713686f37b796577b31e1d3b0/examples/android/app/src/main/java/ai/clova/see/example/ImageProcessor.java#L78
위 함수의 실제 동작은 NV21 image를 flat buffer로 복사하는 것으로, YUV 값의 복사본을 만드는 과정입니다. 이 부분의 구현이 emulator에서의 동작을 고려하지 않았기 때문에 발생하였습니다.

Android에서 android.media.Image는 mFormat의 값에 따라 각각 다른 값을 가지고 있게 되는데요. Android 실제 기기(Pixel 6 Pro)와 emulator에서 모두 mFormat 값이 35였고, 이는 [공식문서](https://developer.android.com/reference/android/graphics/ImageFormat#YUV_420_888)에 따르면 `YUV_420_888`을 의미합니다. 이 format은 [Chroma subsampling](https://en.wikipedia.org/wiki/Chroma_subsampling) 형식으로 pixel 값들이 저장되어 있음을 의미하는데요.

![image](https://user-images.githubusercontent.com/3060991/201368506-8181db9d-f2d9-4cef-a81e-f5e5f34c3c51.png)
- 출처: https://en.wikipedia.org/wiki/File:Yuv420.svg

문제의 원인은 실제 기기에서의 Image가 가지는 UV plane의 pixel stride와 emulator에서의 Image가 가지는 UV plane의 pixel stride가 서로 다르다는 것이었습니다.

|실제 device의 UV pixel stride|emulator의 UV pixel stride|
|:-:|:-:|
|<img width="258" alt="device_pixel_stride" src="https://user-images.githubusercontent.com/3060991/201369594-8d710a3a-86e0-48d5-a719-86ed29e998ee.png">|<img width="249" alt="emulator_pixel_stride" src="https://user-images.githubusercontent.com/3060991/201369190-7d5b6388-e4a4-4a0b-a5b6-df17005ffe9f.png">|
- 출처: 직접 capture

 이는 Android의 경우 카메라로부터 가져온 image를 YUV420sp, 흔히 NV21이라 하는 format으로 전달하기 때문인데요. NV21과 YUV420p의 차이는 UV 영역이 구분되어 있느냐(YUV420p) 아니면 같은 영역에 interleave 되어 있느냐의 차이입니다. NV21은 V가 먼저 있는 형식이고 비슷한 NV12는 U가 먼저오는 형식입니다.

<image alt="YUV_420_888" src="https://gist.githubusercontent.com/Jim-Bar/3cbba684a71d1a9d468a6711a6eddbeb/raw/656de03d44d16517f9067943111c0a30bfa8ae05/YUV_formats.png">

- 출처: https://gist.github.com/Jim-Bar/3cbba684a71d1a9d468a6711a6eddbeb#file-yuv_formats-png

앞선 함수에서 YUV 값을 flat buffer로 복사하는 과정에서 NV21 format임을 가정하여 Y와 U의 주소만 가지고 복사를 하도록 구성되어 있었습니다. 그러나 emulator에서는 I420 형식이기 때문에 NV21 format으로 바꾸기 위해서는 U와 V를 interleave 하여 복사를 해야 합니다. ByteBuffer는 get()을 이용하면 U와 V의 byte를 가져올 수 있도록 추상화 되어 있으므로, 이를 이용하여 NV21 형식으로 변환시켜 보았고 emulator와 실제 장비에서 동작함을 확인하였습니다.

stride와 U, V의 시작주소값을 비교하여 YUV 이미지를 RGB로 변환하는 방식은 [Android에서 사용 중인 libyuv가 YUV image를 ARGB로 변환하는 방식](https://cs.android.com/android/platform/superproject/+/master:external/libyuv/files/source/convert_argb.cc;drc=51738d52b6c91d4573b75f6483dd045d0affc00b;l=4129)입니다.

Sample app에서 사용 중인 camerax의 version이 낮아 [ImageAnalysis에 setOutputImageFormat](https://developer.android.com/reference/kotlin/androidx/camera/core/ImageAnalysis.Builder#setOutputImageFormat(int))을 RGB로 지정해보지 못하였습니다. 임의로 camerax의 version을 1.1.0 이상으로 변경하였을 경우 build error가 발생하였고, 이를 수정하기보다 workaround를 소개해 드리는 것이 빠를 것 같아 간단히 작성하여 공유드립니다. 위 `setOutputImageFormat`으로 [OUTPUT_IMAGE_FORMAT_RGBA_8888](https://developer.android.com/reference/kotlin/androidx/camera/core/ImageAnalysis#OUTPUT_IMAGE_FORMAT_RGBA_8888())을 지정하면, Android 내부에서 libyuv를 이용해 RGBA로 변경된 ImageProxy가 Analyzer의 analyze() 함수에 전달됩니다.
참조: https://developer.android.com/training/camerax/analyze#create-analyzer

현재 sample app에서 사용 중인 YUV2RGB의 구현 내용을 보았을 때, ImageAnalysis의 output을 로 변경하고 그 결과로 부터 Bitmap을 만들어 이용하여도 결과값이 잘 나올 것으로 추측합니다. 만약 사용하시는 camerax의 version이 1.1.0 이상이라면 시도해 보시는 것도 좋을 것 같습니다.


감사합니다. :)

**Comment by junhee-yoo** [comment]
> > 안녕하세요. :)
> > Webcam으로 들어오는 영상이더라도 Face 정보가 잡혀야 맞을 것 같은데요. 혹 camera의 출력을 그대로 넘기신게 아닌가 추측이 됩니다.
> > https://github.com/naver/clova-face-kit/blob/9d28cf49b5d9dc0713686f37b796577b31e1d3b0/examples/android/app/src/main/java/ai/clova/see/example/CameraFragment.kt#L392
> > 
> > 이 부분을 참고하여 설정 및 instance 생성 부분을 한번 확인해 보시겠어요?
> 
> android sample code clone후 실행 했는데도 같은 현상 발생하며 아래 에러 로그가 발생하는데 저 로그가 분석이 안되는 원인일까요? W/libc: Access denied finding property "ro.hardware.chipname" W/ncnn: syscall error -1

말씀주신 log는:
1. cpu info를 조회하였으나 해당 속성을 찾지 못함.
2. 성능향상을 위해 sched_affinity를 설정하는 과정에서 syscall 호출 결과 실패함.

을 의미합니다.


감사합니다. :)

**Comment by Sungsoooo** [comment]
보내주신 내용 확인하고 적용해보니 정상 작동하였습니다.
감사합니다 :)

**Comment by junhee-yoo** [comment]
@Sungsoooo 감사합니다.
issue close 하겠습니다. 🙇‍♂️
